import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import "./styles/style_1.css";
// import "./styles/style_2.css";
import "./styles/style_3.css";
import "./styles/style_main.css";

import "@fortawesome/fontawesome-free/css/all.min.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Enhanced Translation Dictionary",
  description: "Generated by create next app",
  icons: {
    icon: "https://cdn-icons-png.flaticon.com/512/3898/3898082.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable ?? ""} ${geistMono.variable ?? ""} antialiased`}
      >
        {children}

        {/* Scripts that must load on client */}
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="./js/script_system_1.js"></script>
        <script src="./js/script_main.js"></script>

        {/* External stylesheets */}
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          rel="stylesheet"
        />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          rel="stylesheet"
        />

      </body>
    </html>
  );
}
